// Purpose: To store testimonials data for testing purposes.

export const testimonialsData = [
  {
    name: "Ahmet Yıldız",
    rating: 5,
    comment: "Ben daha önce papatya çayı içmemişim, onu anladım",
    productImage: "https://placehold.co/300x200?text=Organik+Papatya+Çayı",
    userImage: "https://randomuser.me/api/portraits/men/75.jpg",
    product: "Organik Papatya Çayı",
  },
  {
    name: "Fatma Kaya",
    rating: 4,
    comment: "Cildim için kullandığım en iyi doğal krem",
    productImage: "https://placehold.co/300x200?text=Nemlendirici+Doğal+Krem",
    userImage: "https://randomuser.me/api/portraits/women/75.jpg",
    product: "Nemlendirici Doğal Krem",
  },
  {
    name: "Merve Çelik",
    rating: 5,
    comment: "Üskümenzade'nin müşteri hizmetleri harika",
    productImage: "https://placehold.co/300x200?text=Bitkisel+Karışım+Çayı",
    userImage: "https://randomuser.me/api/portraits/women/74.jpg",
    product: "Bitkisel Karışım Çayı",
  },
  {
    name: "Ali Vural",
    rating: 3,
    comment: "Çay güzel ama biraz daha aromalı olabilirdi",
    productImage: "https://placehold.co/300x200?text=Organik+Yeşil+Çay",
    userImage: "https://randomuser.me/api/portraits/men/74.jpg",
    product: "Organik Yeşil Çay",
  },
  {
    name: "Ayşe Demir",
    rating: 4,
    comment: "Çok lezzetli ve ferahlatıcı bir çay",
    productImage: "https://placehold.co/300x200?text=Organik+Yeşil+Çay",
    userImage: "https://randomuser.me/api/portraits/women/73.jpg",
    product: "Organik Yeşil Çay",
  },
  {
    name: "Burak Can",
    rating: 5,
    comment: "El kremi çok hafif ve nemlendirici etkisi harika",
    productImage: "https://placehold.co/300x200?text=Doğal+El+Kremi",
    userImage: "https://randomuser.me/api/portraits/men/73.jpg",
    product: "Doğal El Kremi",
  },
  {
    name: "Elif Nur",
    rating: 5,
    comment: "Vegan sabunlar gerçekten muhteşem kokuyor",
    productImage: "https://placehold.co/300x200?text=El+Yapımı+Vegan+Sabun",
    userImage: "https://randomuser.me/api/portraits/women/71.jpg",
    product: "El Yapımı Vegan Sabun",
  },
  {
    name: "Hakan Yılmaz",
    rating: 4,
    comment: "Keşke daha büyük boyutu olsaydı ama kokusu harika",
    productImage: "https://placehold.co/300x200?text=Lavanta+Esansiyel+Yağı",
    userImage: "https://randomuser.me/api/portraits/men/71.jpg",
    product: "Lavanta Esansiyel Yağı",
  },
  {
    name: "Sena Çelik",
    rating: 5,
    comment: "Uyku çayı gerçekten işe yarıyor, rahat bir uyku çekiyorum",
    productImage:
      "https://placehold.co/300x200?text=Uyku+Rahatlatıcı+Bitki+Çayı",
    userImage: "https://randomuser.me/api/portraits/women/70.jpg",
    product: "Uyku Rahatlatıcı Bitki Çayı",
  },
  {
    name: "Okan Karadeniz",
    rating: 4,
    comment: "Tadı bildiğiniz çaylardan çok daha güzel",
    productImage: "https://placehold.co/300x200?text=Organik+Papatya+Çayı",
    userImage: "https://randomuser.me/api/portraits/men/70.jpg",
    product: "Organik Papatya Çayı",
  },
  {
    name: "Zeynep Güler",
    rating: 5,
    comment: "Mükemmel cilt yağı! Kuru cildimi harika bir şekilde besliyor.",
    productImage: "https://placehold.co/300x200?text=Doğal+Vücut+Yağı",
    userImage: "https://randomuser.me/api/portraits/women/69.jpg",
    product: "Doğal Vücut Yağı",
  },
  {
    name: "Cemil Uçar",
    rating: 3,
    comment: "Sabunun kokusu çok güzel ama biraz daha uzun süre dayanabilirdi.",
    productImage: "https://placehold.co/300x200?text=El+Yapımı+Vegan+Sabun",
    userImage: "https://randomuser.me/api/portraits/men/69.jpg",
    product: "El Yapımı Vegan Sabun",
  },
];
